# Generated by Django 3.1.7 on 2021-04-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstateApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=100)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='shop/images/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='shop/images')),
            ],
            options={
                'unique_together': {('country', 'state', 'city', 'street', 'house_number')},
            },
        ),
        migrations.CreateModel(
            name='EstatePurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='shop.estateapplication')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalEstateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_images', to='shop.estateapplication')),
            ],
            options={
                'default_related_name': 'estate_images',
            },
        ),
    ]
